# Generated by Django 3.1.3 on 2020-11-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicina',
            name='fecha_fabricacion',
            field=models.DateField(default=1983),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicina',
            name='fecha_vencimiento',
            field=models.DateField(default=1989),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicina',
            name='tipo_medicamento',
            field=models.CharField(choices=[('G', 'Generico'), ('C', 'Comercial')], default=1, max_length=12),
            preserve_default=False,
        ),
    ]
