# Generated by Django 3.1.3 on 2020-11-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dato',
            old_name='nombre',
            new_name='nombres',
        ),
        migrations.AddField(
            model_name='dato',
            name='apellidos',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dato',
            name='direccion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dato',
            name='edad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dato',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dato',
            name='fecha_nacimiento',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dato',
            name='identificacion',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dato',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dato',
            name='telefono',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dato',
            name='tipo_identificacion',
            field=models.CharField(choices=[('RE', 'Registro Civil'), ('TI', 'Tarjeta Identidad'), ('CE', 'Cedula')], default=1, max_length=12),
            preserve_default=False,
        ),
    ]
